alertmanager:
  enabled: false
kubeStateMetrics:
  enabled: false
pushgateway:
  enabled: false
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    path: /
    pathType: Prefix  
    hosts:
      - ${ingress_domain}
  persistentVolume:
    enabled: true
    storageClass: ocloud-ssd-standard
    size: 50Gi
serverFiles:
  prometheus.yml:
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
    ## Below two files are DEPRECATED will be removed from this default values file
      - /etc/config/rules
      - /etc/config/alerts

    scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets:
            - localhost:9090
      - job_name: nodes
        consul_sd_configs:
        - datacenter: dc1
          server: obs-consul-consul-server.observability.svc.cluster.local:8500
          services:
          - observability